default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5
  username: ubuntu
  password: password

development:
  <<: *default
  database: about_me_app_development

test:
  <<: *default
  database: about_me_app_test

production:
  <<: *default
  database: about_me_app_production